# -*- coding: utf-8 -*-
"""CSE602 Final Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18D3bLb2f_gHclJ1WP46xZqPlQPiofn7n

# 1. Download and Load the Training, Test and Validation Datasets

Data source: [BOston Neonatal Brain Injury Data](https://zenodo.org/records/10602767)
"""

!wget https://zenodo.org/records/10602767/files/BONBID2023_Train.zip?download=1 -O train_data.zip
!wget https://zenodo.org/records/10602767/files/BONBID2023_Test.zip?download=1 -O test_data.zip
!wget https://zenodo.org/records/10602767/files/BONBID2023_Val.zip?download=1 -O val_data.zip
!wget https://zenodo.org/records/10602767/files/atlases.tar.gz?download=1 -O atlases.tar.gz

!unzip /content/train_data.zip

!pip install SimpleITK # A special package to read in and view medical images

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sklearn as skl
import SimpleITK as sitk
import tensorflow as tf
from tensorflow import keras

#Some basic EDA; we read in and visualise the first five images to get a glimpse of the data we'll be dealing with.


data_dir = '/content/BONBID2023_Train'

for i in [10, 14, 15, 28, 62]:
  train_image = sitk.ReadImage(f"{data_dir}/1ADC_ss/MGHNICU_0{i}-VISIT_01-ADC_ss.mha")
  train_array = sitk.GetArrayFromImage(train_image)
  mid_slice = train_array.shape[0] // 2

  plt.figure(figsize=(8, 6))
  plt.imshow(train_array[mid_slice, :, :], cmap = 'gray')
  plt.title(f"Slice {mid_slice}, Image {i}")
  plt.axis('off')
  plt.show()